# Generated by Django 5.2.7 on 2025-10-17 14:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SessionApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='session',
            options={'verbose_name': 'Session', 'verbose_name_plural': 'Sessions'},
        ),
        migrations.AlterField(
            model_name='session',
            name='room',
            field=models.CharField(max_length=80, validators=[django.core.validators.RegexValidator(message='Room must contain only letters, digits, spaces or hyphens.', regex='^[A-Za-z0-9\\- ]+$')]),
        ),
    ]
