# Generated by Django 5.2.7 on 2025-10-17 14:42

import ConferenceApp.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ConferenceApp', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conference',
            name='description',
            field=models.TextField(validators=[django.core.validators.MinLengthValidator(30, message='Description must be at least 30 characters.')]),
        ),
        migrations.AlterField(
            model_name='conference',
            name='title',
            field=models.CharField(max_length=200, validators=[django.core.validators.RegexValidator(message='Title must contain only letters and spaces.', regex='^[A-Za-zÀ-ÖØ-öø-ÿ ]+$')]),
        ),
        migrations.AlterField(
            model_name='submission',
            name='keywords',
            field=models.CharField(max_length=300, validators=[ConferenceApp.models.validate_keywords_max10]),
        ),
        migrations.AlterField(
            model_name='submission',
            name='paper',
            field=models.FileField(upload_to='papers/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])]),
        ),
    ]
