# Generated by Django 5.2.7 on 2025-10-17 15:44

import ConferenceApp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ConferenceApp', '0003_alter_conference_description_alter_conference_title_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='submission',
            name='id',
        ),
        migrations.AddField(
            model_name='submission',
            name='submission_id',
            field=models.CharField(default=ConferenceApp.models.generate_submission_id, editable=False, max_length=255, primary_key=True, serialize=False, unique=True),
        ),
    ]
