# Generated by Django 5.2.7 on 2025-10-17 14:42

import UserApp.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'Utulisateur', 'verbose_name_plural': 'Utulisateurs'},
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, unique=True, validators=[UserApp.models.validate_user_email_domain]),
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(max_length=150, validators=[django.core.validators.RegexValidator(message='Only letters, spaces, and hyphens are allowed.', regex='^[A-Za-zÀ-ÖØ-öø-ÿ\\- ]+$')]),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(max_length=150, validators=[django.core.validators.RegexValidator(message='Only letters, spaces, and hyphens are allowed.', regex='^[A-Za-zÀ-ÖØ-öø-ÿ\\- ]+$')]),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_id',
            field=models.CharField(editable=False, max_length=8, primary_key=True, serialize=False, unique=True, validators=[django.core.validators.MinLengthValidator(8)]),
        ),
    ]
